site:
  url: https://jakarta.ee
  title: Jakarta EE Documentation
  start_page: jakarta-ee-tutorial::index.adoc

content:
  # branches will be updated when PRs are merged
  sources:
  - url: https://github.com/virtua-tech/jakartaee-tutorial.git
    start_paths:
      - src/main/antora
    branches:
      - release/8
      - release/9.1
      - main

urls:
  latest_version_segment: current

ui:
  bundle:
    url: https://github.com/virtua-tech/jakartaee-tutorial-ui/releases/download/latest/ui-bundle.zip
    snapshot: true

runtime:
  log:
    level: debug

antora:
  extensions:
  - '@antora/lunr-extension'
  - '@antora/pdf-extension'
