name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: install-jhdk
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - id: build
        name: Build Docs
        run: mvn -B clean verify
  deploy:
    name: Deploy Docs to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

#    if: github.ref == 'refs/heads/main'
    steps:
      - id: create-artifact
        name: Create Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/generated-docs
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2



